services:
  - type: web
    name: atelier-store
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: atelier-postgres
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_TOKEN
        generateValue: true
    healthCheckPath: /health

databases:
  - name: atelier-postgres
    plan: free
    databaseName: atelier_db
    user: atelier_user
